services:
  # ---------------- Kafka (KRaft) ----------------
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka-dbz
    hostname: kafka-dbz
    ports:
      - "29092:9092"   # host port changed to avoid conflicts
    environment:
      CLUSTER_ID: 5Yr1I-7cT_i1u2a3b4c5d6
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-dbz:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-dbz:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - debezium-net

  # ---------------- Debezium Connect ----------------
  connect:
    image: debezium/connect:2.6
    container_name: dbz-connect
    hostname: dbz-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka-dbz:9092
      GROUP_ID: debezium-connect-group

      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      REST_PORT: 8083
      REST_ADVERTISED_HOST_NAME: dbz-connect
      CONNECT_PLUGIN_PATH: /kafka/connect,/kafka/connect/debezium,/kafka/connect/sink
    depends_on:
      - kafka
      - postgres
    networks:
      - debezium-net

    # ---------------- PostgreSQL ----------------
  postgres:
    image: postgres:17.5-bullseye
    container_name: postgres-dbz
    hostname: postgres-dbz
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: itpuser
      POSTGRES_PASSWORD: itp@1234
      POSTGRES_DB: itp_db
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
      -c listen_addresses='*'
      -c shared_preload_libraries=pgoutput
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - debezium-net


  # ---------------- Kafka UI ----------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: dbz-kafka-ui
    ports:
      - "8099:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-dbz:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://dbz-connect:8083
    depends_on:
      - kafka
      - connect
    networks:
      - debezium-net

networks:
  debezium-net:
    driver: bridge

volumes:
  pg-data:
  kafka-data:







